Integrating ZeroMQ and Simple Python Demo
DCP-CloudMesh/CloudMesh pull request #11
Opened 2024-11-20 20:44 UTC by rayaq-siddiqui

2024-11-21 18:37 UTC, rayaq-siddiqui commented
It seems like the "empty" files are added because of permission changes in the repo. So it is not relevant to the PR and not causing changes. The non-empty files are the only impactful changes in this repo.

2024-11-23 22:55 UTC, PalaashKolhe requested changes

2024-11-23 22:55 UTC, PalaashKolhe commented on src/Peers/provider.cpp
> +        // zmq_sender.send("P2P: task request received!");
nit: comment left behind

2024-11-23 22:55 UTC, PalaashKolhe commented on src/Peers/provider.cpp
> +    // sort(data.begin(), data.end());
nit: comment

2024-11-23 22:55 UTC, PalaashKolhe commented on third_party/MODULE.bazel
is this file used? if not, can we get rid of it?

2024-11-23 22:56 UTC, rayaq-siddiqui commented on third_party/MODULE.bazel
Yes, required to be able to recognize it as a Bazel module. I tried removing it and it would not build.

2024-11-26 14:40 UTC, TonyxSun approved these changes
I am able to build and run this with 3 providers; great work!!!!!

2024-11-27 03:56 UTC, PalaashKolhe approved these changes

2024-11-27 04:14 UTC, merged